version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose port 8000 on the host
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"  # Use environment variable for the API key
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8000'  # Run the FastAPI app
    container_name: fastapi-app  # Custom container name
    restart: unless-stopped  # Restart the container unless explicitly stopped